### ISSUE TITLE
Provide symbols on nuget.org

### ISSUE THREAD

**Issue by PieterjanDeClippel** [IdentityServer/IdentityServer4#5107]
### Suggestion

Is it possible to provide the symbols through nuget.org?
This would make it easier for debugging issues in our projects.

1) Modify csproj - Add `<IncludeSymbols>true</IncludeSymbols><SymbolPackageFormat>snupkg</SymbolPackageFormat>` to the first `PropertyGroup`
2) You can setup a GitHub action like this to push to nuget.org (optionally to github.com)

```
name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.301
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Release MintPlayer.SeasonChecker/MintPlayer.SeasonChecker.csproj
    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.PUBLISH_TO_NUGET_ORG }} --skip-duplicate
    - name: PushGithub
      run: nuget.exe push "**/*.nupkg" -NoSymbols -SkipDuplicate
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
```

3) GitHub Packages doesn't provide a symbol server.

### Minimal working example

See [the following action](https://github.com/MintPlayer/MintPlayer.MVVM/blob/master/.github/workflows/dotnet-core.yml)

### Help

If necessary, I'm willing to help with this setup
